sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t aschmitt/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aschmitt/docker-react npm run test